// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package message_test

import (
	"sync"
)

var (
	lockMarshallerMockMarshal sync.RWMutex
)

// MarshallerMock is a mock implementation of Marshaller.
//
//     func TestSomethingThatUsesMarshaller(t *testing.T) {
//
//         // make and configure a mocked Marshaller
//         mockedMarshaller := &MarshallerMock{
//             MarshalFunc: func(s interface{}) ([]byte, error) {
// 	               panic("TODO: mock out the Marshal method")
//             },
//         }
//
//         // TODO: use mockedMarshaller in code that requires Marshaller
//         //       and then make assertions.
//
//     }
type MarshallerMock struct {
	// MarshalFunc mocks the Marshal method.
	MarshalFunc func(s interface{}) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Marshal holds details about calls to the Marshal method.
		Marshal []struct {
			// S is the s argument value.
			S interface{}
		}
	}
}

// Marshal calls MarshalFunc.
func (mock *MarshallerMock) Marshal(s interface{}) ([]byte, error) {
	if mock.MarshalFunc == nil {
		panic("moq: MarshallerMock.MarshalFunc is nil but Marshaller.Marshal was just called")
	}
	callInfo := struct {
		S interface{}
	}{
		S: s,
	}
	lockMarshallerMockMarshal.Lock()
	mock.calls.Marshal = append(mock.calls.Marshal, callInfo)
	lockMarshallerMockMarshal.Unlock()
	return mock.MarshalFunc(s)
}

// MarshalCalls gets all the calls that were made to Marshal.
// Check the length with:
//     len(mockedMarshaller.MarshalCalls())
func (mock *MarshallerMock) MarshalCalls() []struct {
	S interface{}
} {
	var calls []struct {
		S interface{}
	}
	lockMarshallerMockMarshal.RLock()
	calls = mock.calls.Marshal
	lockMarshallerMockMarshal.RUnlock()
	return calls
}
