// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storertest

import (
	"context"
	"github.com/ONSdigital/dp-dimension-importer/store"
	"github.com/ONSdigital/dp-graph/v2/models"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that StorerMock does implement store.Storer.
// If this is not the case, regenerate this file with moq.
var _ store.Storer = &StorerMock{}

// StorerMock is a mock implementation of store.Storer.
//
//     func TestSomethingThatUsesStorer(t *testing.T) {
//
//         // make and configure a mocked store.Storer
//         mockedStorer := &StorerMock{
//             AddDimensionsFunc: func(ctx context.Context, instanceID string, dimensions []interface{}) error {
// 	               panic("mock out the AddDimensions method")
//             },
//             AddVersionDetailsToInstanceFunc: func(ctx context.Context, instanceID string, datasetID string, edition string, version int) error {
// 	               panic("mock out the AddVersionDetailsToInstance method")
//             },
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             CountInsertedObservationsFunc: func(ctx context.Context, instanceID string) (int64, error) {
// 	               panic("mock out the CountInsertedObservations method")
//             },
//             CreateCodeRelationshipFunc: func(ctx context.Context, instanceID string, codeListID string, code string) error {
// 	               panic("mock out the CreateCodeRelationship method")
//             },
//             CreateInstanceFunc: func(ctx context.Context, instanceID string, csvHeaders []string) error {
// 	               panic("mock out the CreateInstance method")
//             },
//             CreateInstanceConstraintFunc: func(ctx context.Context, instanceID string) error {
// 	               panic("mock out the CreateInstanceConstraint method")
//             },
//             InsertDimensionFunc: func(ctx context.Context, cache map[string]string, instanceID string, dimension *models.Dimension) (*models.Dimension, error) {
// 	               panic("mock out the InsertDimension method")
//             },
//             InstanceExistsFunc: func(ctx context.Context, instanceID string) (bool, error) {
// 	               panic("mock out the InstanceExists method")
//             },
//             SetInstanceIsPublishedFunc: func(ctx context.Context, instanceID string) error {
// 	               panic("mock out the SetInstanceIsPublished method")
//             },
//         }
//
//         // use mockedStorer in code that requires store.Storer
//         // and then make assertions.
//
//     }
type StorerMock struct {
	// AddDimensionsFunc mocks the AddDimensions method.
	AddDimensionsFunc func(ctx context.Context, instanceID string, dimensions []interface{}) error

	// AddVersionDetailsToInstanceFunc mocks the AddVersionDetailsToInstance method.
	AddVersionDetailsToInstanceFunc func(ctx context.Context, instanceID string, datasetID string, edition string, version int) error

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// CountInsertedObservationsFunc mocks the CountInsertedObservations method.
	CountInsertedObservationsFunc func(ctx context.Context, instanceID string) (int64, error)

	// CreateCodeRelationshipFunc mocks the CreateCodeRelationship method.
	CreateCodeRelationshipFunc func(ctx context.Context, instanceID string, codeListID string, code string) error

	// CreateInstanceFunc mocks the CreateInstance method.
	CreateInstanceFunc func(ctx context.Context, instanceID string, csvHeaders []string) error

	// CreateInstanceConstraintFunc mocks the CreateInstanceConstraint method.
	CreateInstanceConstraintFunc func(ctx context.Context, instanceID string) error

	// InsertDimensionFunc mocks the InsertDimension method.
	InsertDimensionFunc func(ctx context.Context, cache map[string]string, instanceID string, dimension *models.Dimension) (*models.Dimension, error)

	// InstanceExistsFunc mocks the InstanceExists method.
	InstanceExistsFunc func(ctx context.Context, instanceID string) (bool, error)

	// SetInstanceIsPublishedFunc mocks the SetInstanceIsPublished method.
	SetInstanceIsPublishedFunc func(ctx context.Context, instanceID string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddDimensions holds details about calls to the AddDimensions method.
		AddDimensions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
			// Dimensions is the dimensions argument value.
			Dimensions []interface{}
		}
		// AddVersionDetailsToInstance holds details about calls to the AddVersionDetailsToInstance method.
		AddVersionDetailsToInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
			// DatasetID is the datasetID argument value.
			DatasetID string
			// Edition is the edition argument value.
			Edition string
			// Version is the version argument value.
			Version int
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountInsertedObservations holds details about calls to the CountInsertedObservations method.
		CountInsertedObservations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
		// CreateCodeRelationship holds details about calls to the CreateCodeRelationship method.
		CreateCodeRelationship []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
			// CodeListID is the codeListID argument value.
			CodeListID string
			// Code is the code argument value.
			Code string
		}
		// CreateInstance holds details about calls to the CreateInstance method.
		CreateInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
			// CsvHeaders is the csvHeaders argument value.
			CsvHeaders []string
		}
		// CreateInstanceConstraint holds details about calls to the CreateInstanceConstraint method.
		CreateInstanceConstraint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
		// InsertDimension holds details about calls to the InsertDimension method.
		InsertDimension []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cache is the cache argument value.
			Cache map[string]string
			// InstanceID is the instanceID argument value.
			InstanceID string
			// Dimension is the dimension argument value.
			Dimension *models.Dimension
		}
		// InstanceExists holds details about calls to the InstanceExists method.
		InstanceExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
		// SetInstanceIsPublished holds details about calls to the SetInstanceIsPublished method.
		SetInstanceIsPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
	lockAddDimensions               sync.RWMutex
	lockAddVersionDetailsToInstance sync.RWMutex
	lockChecker                     sync.RWMutex
	lockClose                       sync.RWMutex
	lockCountInsertedObservations   sync.RWMutex
	lockCreateCodeRelationship      sync.RWMutex
	lockCreateInstance              sync.RWMutex
	lockCreateInstanceConstraint    sync.RWMutex
	lockInsertDimension             sync.RWMutex
	lockInstanceExists              sync.RWMutex
	lockSetInstanceIsPublished      sync.RWMutex
}

// AddDimensions calls AddDimensionsFunc.
func (mock *StorerMock) AddDimensions(ctx context.Context, instanceID string, dimensions []interface{}) error {
	if mock.AddDimensionsFunc == nil {
		panic("StorerMock.AddDimensionsFunc: method is nil but Storer.AddDimensions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
		Dimensions []interface{}
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
		Dimensions: dimensions,
	}
	mock.lockAddDimensions.Lock()
	mock.calls.AddDimensions = append(mock.calls.AddDimensions, callInfo)
	mock.lockAddDimensions.Unlock()
	return mock.AddDimensionsFunc(ctx, instanceID, dimensions)
}

// AddDimensionsCalls gets all the calls that were made to AddDimensions.
// Check the length with:
//     len(mockedStorer.AddDimensionsCalls())
func (mock *StorerMock) AddDimensionsCalls() []struct {
	Ctx        context.Context
	InstanceID string
	Dimensions []interface{}
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
		Dimensions []interface{}
	}
	mock.lockAddDimensions.RLock()
	calls = mock.calls.AddDimensions
	mock.lockAddDimensions.RUnlock()
	return calls
}

// AddVersionDetailsToInstance calls AddVersionDetailsToInstanceFunc.
func (mock *StorerMock) AddVersionDetailsToInstance(ctx context.Context, instanceID string, datasetID string, edition string, version int) error {
	if mock.AddVersionDetailsToInstanceFunc == nil {
		panic("StorerMock.AddVersionDetailsToInstanceFunc: method is nil but Storer.AddVersionDetailsToInstance was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
		DatasetID  string
		Edition    string
		Version    int
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
		DatasetID:  datasetID,
		Edition:    edition,
		Version:    version,
	}
	mock.lockAddVersionDetailsToInstance.Lock()
	mock.calls.AddVersionDetailsToInstance = append(mock.calls.AddVersionDetailsToInstance, callInfo)
	mock.lockAddVersionDetailsToInstance.Unlock()
	return mock.AddVersionDetailsToInstanceFunc(ctx, instanceID, datasetID, edition, version)
}

// AddVersionDetailsToInstanceCalls gets all the calls that were made to AddVersionDetailsToInstance.
// Check the length with:
//     len(mockedStorer.AddVersionDetailsToInstanceCalls())
func (mock *StorerMock) AddVersionDetailsToInstanceCalls() []struct {
	Ctx        context.Context
	InstanceID string
	DatasetID  string
	Edition    string
	Version    int
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
		DatasetID  string
		Edition    string
		Version    int
	}
	mock.lockAddVersionDetailsToInstance.RLock()
	calls = mock.calls.AddVersionDetailsToInstance
	mock.lockAddVersionDetailsToInstance.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *StorerMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("StorerMock.CheckerFunc: method is nil but Storer.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedStorer.CheckerCalls())
func (mock *StorerMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *StorerMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("StorerMock.CloseFunc: method is nil but Storer.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedStorer.CloseCalls())
func (mock *StorerMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CountInsertedObservations calls CountInsertedObservationsFunc.
func (mock *StorerMock) CountInsertedObservations(ctx context.Context, instanceID string) (int64, error) {
	if mock.CountInsertedObservationsFunc == nil {
		panic("StorerMock.CountInsertedObservationsFunc: method is nil but Storer.CountInsertedObservations was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
	}
	mock.lockCountInsertedObservations.Lock()
	mock.calls.CountInsertedObservations = append(mock.calls.CountInsertedObservations, callInfo)
	mock.lockCountInsertedObservations.Unlock()
	return mock.CountInsertedObservationsFunc(ctx, instanceID)
}

// CountInsertedObservationsCalls gets all the calls that were made to CountInsertedObservations.
// Check the length with:
//     len(mockedStorer.CountInsertedObservationsCalls())
func (mock *StorerMock) CountInsertedObservationsCalls() []struct {
	Ctx        context.Context
	InstanceID string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
	}
	mock.lockCountInsertedObservations.RLock()
	calls = mock.calls.CountInsertedObservations
	mock.lockCountInsertedObservations.RUnlock()
	return calls
}

// CreateCodeRelationship calls CreateCodeRelationshipFunc.
func (mock *StorerMock) CreateCodeRelationship(ctx context.Context, instanceID string, codeListID string, code string) error {
	if mock.CreateCodeRelationshipFunc == nil {
		panic("StorerMock.CreateCodeRelationshipFunc: method is nil but Storer.CreateCodeRelationship was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
		CodeListID string
		Code       string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
		CodeListID: codeListID,
		Code:       code,
	}
	mock.lockCreateCodeRelationship.Lock()
	mock.calls.CreateCodeRelationship = append(mock.calls.CreateCodeRelationship, callInfo)
	mock.lockCreateCodeRelationship.Unlock()
	return mock.CreateCodeRelationshipFunc(ctx, instanceID, codeListID, code)
}

// CreateCodeRelationshipCalls gets all the calls that were made to CreateCodeRelationship.
// Check the length with:
//     len(mockedStorer.CreateCodeRelationshipCalls())
func (mock *StorerMock) CreateCodeRelationshipCalls() []struct {
	Ctx        context.Context
	InstanceID string
	CodeListID string
	Code       string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
		CodeListID string
		Code       string
	}
	mock.lockCreateCodeRelationship.RLock()
	calls = mock.calls.CreateCodeRelationship
	mock.lockCreateCodeRelationship.RUnlock()
	return calls
}

// CreateInstance calls CreateInstanceFunc.
func (mock *StorerMock) CreateInstance(ctx context.Context, instanceID string, csvHeaders []string) error {
	if mock.CreateInstanceFunc == nil {
		panic("StorerMock.CreateInstanceFunc: method is nil but Storer.CreateInstance was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
		CsvHeaders []string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
		CsvHeaders: csvHeaders,
	}
	mock.lockCreateInstance.Lock()
	mock.calls.CreateInstance = append(mock.calls.CreateInstance, callInfo)
	mock.lockCreateInstance.Unlock()
	return mock.CreateInstanceFunc(ctx, instanceID, csvHeaders)
}

// CreateInstanceCalls gets all the calls that were made to CreateInstance.
// Check the length with:
//     len(mockedStorer.CreateInstanceCalls())
func (mock *StorerMock) CreateInstanceCalls() []struct {
	Ctx        context.Context
	InstanceID string
	CsvHeaders []string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
		CsvHeaders []string
	}
	mock.lockCreateInstance.RLock()
	calls = mock.calls.CreateInstance
	mock.lockCreateInstance.RUnlock()
	return calls
}

// CreateInstanceConstraint calls CreateInstanceConstraintFunc.
func (mock *StorerMock) CreateInstanceConstraint(ctx context.Context, instanceID string) error {
	if mock.CreateInstanceConstraintFunc == nil {
		panic("StorerMock.CreateInstanceConstraintFunc: method is nil but Storer.CreateInstanceConstraint was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
	}
	mock.lockCreateInstanceConstraint.Lock()
	mock.calls.CreateInstanceConstraint = append(mock.calls.CreateInstanceConstraint, callInfo)
	mock.lockCreateInstanceConstraint.Unlock()
	return mock.CreateInstanceConstraintFunc(ctx, instanceID)
}

// CreateInstanceConstraintCalls gets all the calls that were made to CreateInstanceConstraint.
// Check the length with:
//     len(mockedStorer.CreateInstanceConstraintCalls())
func (mock *StorerMock) CreateInstanceConstraintCalls() []struct {
	Ctx        context.Context
	InstanceID string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
	}
	mock.lockCreateInstanceConstraint.RLock()
	calls = mock.calls.CreateInstanceConstraint
	mock.lockCreateInstanceConstraint.RUnlock()
	return calls
}

// InsertDimension calls InsertDimensionFunc.
func (mock *StorerMock) InsertDimension(ctx context.Context, cache map[string]string, instanceID string, dimension *models.Dimension) (*models.Dimension, error) {
	if mock.InsertDimensionFunc == nil {
		panic("StorerMock.InsertDimensionFunc: method is nil but Storer.InsertDimension was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Cache      map[string]string
		InstanceID string
		Dimension  *models.Dimension
	}{
		Ctx:        ctx,
		Cache:      cache,
		InstanceID: instanceID,
		Dimension:  dimension,
	}
	mock.lockInsertDimension.Lock()
	mock.calls.InsertDimension = append(mock.calls.InsertDimension, callInfo)
	mock.lockInsertDimension.Unlock()
	return mock.InsertDimensionFunc(ctx, cache, instanceID, dimension)
}

// InsertDimensionCalls gets all the calls that were made to InsertDimension.
// Check the length with:
//     len(mockedStorer.InsertDimensionCalls())
func (mock *StorerMock) InsertDimensionCalls() []struct {
	Ctx        context.Context
	Cache      map[string]string
	InstanceID string
	Dimension  *models.Dimension
} {
	var calls []struct {
		Ctx        context.Context
		Cache      map[string]string
		InstanceID string
		Dimension  *models.Dimension
	}
	mock.lockInsertDimension.RLock()
	calls = mock.calls.InsertDimension
	mock.lockInsertDimension.RUnlock()
	return calls
}

// InstanceExists calls InstanceExistsFunc.
func (mock *StorerMock) InstanceExists(ctx context.Context, instanceID string) (bool, error) {
	if mock.InstanceExistsFunc == nil {
		panic("StorerMock.InstanceExistsFunc: method is nil but Storer.InstanceExists was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
	}
	mock.lockInstanceExists.Lock()
	mock.calls.InstanceExists = append(mock.calls.InstanceExists, callInfo)
	mock.lockInstanceExists.Unlock()
	return mock.InstanceExistsFunc(ctx, instanceID)
}

// InstanceExistsCalls gets all the calls that were made to InstanceExists.
// Check the length with:
//     len(mockedStorer.InstanceExistsCalls())
func (mock *StorerMock) InstanceExistsCalls() []struct {
	Ctx        context.Context
	InstanceID string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
	}
	mock.lockInstanceExists.RLock()
	calls = mock.calls.InstanceExists
	mock.lockInstanceExists.RUnlock()
	return calls
}

// SetInstanceIsPublished calls SetInstanceIsPublishedFunc.
func (mock *StorerMock) SetInstanceIsPublished(ctx context.Context, instanceID string) error {
	if mock.SetInstanceIsPublishedFunc == nil {
		panic("StorerMock.SetInstanceIsPublishedFunc: method is nil but Storer.SetInstanceIsPublished was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		InstanceID string
	}{
		Ctx:        ctx,
		InstanceID: instanceID,
	}
	mock.lockSetInstanceIsPublished.Lock()
	mock.calls.SetInstanceIsPublished = append(mock.calls.SetInstanceIsPublished, callInfo)
	mock.lockSetInstanceIsPublished.Unlock()
	return mock.SetInstanceIsPublishedFunc(ctx, instanceID)
}

// SetInstanceIsPublishedCalls gets all the calls that were made to SetInstanceIsPublished.
// Check the length with:
//     len(mockedStorer.SetInstanceIsPublishedCalls())
func (mock *StorerMock) SetInstanceIsPublishedCalls() []struct {
	Ctx        context.Context
	InstanceID string
} {
	var calls []struct {
		Ctx        context.Context
		InstanceID string
	}
	mock.lockSetInstanceIsPublished.RLock()
	calls = mock.calls.SetInstanceIsPublished
	mock.lockSetInstanceIsPublished.RUnlock()
	return calls
}
