// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-dimension-importer/event"
	"github.com/ONSdigital/dp-dimension-importer/message"
	"sync"
)

var (
	lockInstanceEventHandlerMockHandle sync.RWMutex
)

// Ensure, that InstanceEventHandlerMock does implement message.InstanceEventHandler.
// If this is not the case, regenerate this file with moq.
var _ message.InstanceEventHandler = &InstanceEventHandlerMock{}

// InstanceEventHandlerMock is a mock implementation of message.InstanceEventHandler.
//
//     func TestSomethingThatUsesInstanceEventHandler(t *testing.T) {
//
//         // make and configure a mocked message.InstanceEventHandler
//         mockedInstanceEventHandler := &InstanceEventHandlerMock{
//             HandleFunc: func(e event.NewInstance) error {
// 	               panic("mock out the Handle method")
//             },
//         }
//
//         // use mockedInstanceEventHandler in code that requires message.InstanceEventHandler
//         // and then make assertions.
//
//     }
type InstanceEventHandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(e event.NewInstance) error

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// E is the e argument value.
			E event.NewInstance
		}
	}
}

// Handle calls HandleFunc.
func (mock *InstanceEventHandlerMock) Handle(e event.NewInstance) error {
	if mock.HandleFunc == nil {
		panic("InstanceEventHandlerMock.HandleFunc: method is nil but InstanceEventHandler.Handle was just called")
	}
	callInfo := struct {
		E event.NewInstance
	}{
		E: e,
	}
	lockInstanceEventHandlerMockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	lockInstanceEventHandlerMockHandle.Unlock()
	return mock.HandleFunc(e)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//     len(mockedInstanceEventHandler.HandleCalls())
func (mock *InstanceEventHandlerMock) HandleCalls() []struct {
	E event.NewInstance
} {
	var calls []struct {
		E event.NewInstance
	}
	lockInstanceEventHandlerMockHandle.RLock()
	calls = mock.calls.Handle
	lockInstanceEventHandlerMockHandle.RUnlock()
	return calls
}
