---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.23.2-bullseye

inputs:
  - name: dp-dimension-importer
    path: dp-dimension-importer

outputs:
  - name: build

run:
  path: dp-dimension-importer/ci/scripts/build.sh
